openapi: 3.0.0
info:
  title: Open Banking API v1.0
  description: This an example of an Open Banking API. It is an interface to some common financial microservices.
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/SMARTBEAR_APAC/Demo_3108_2/1.0.0'
    description: SwaggerHub API Auto Mocking
paths:
  /account:
    get:
      tags:
        - developers
      summary: Retrieves account balance
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      operationId: getBalance
      parameters:
        - name: searchString
          in: query
          description: Pass an account ID
          required: false
          style: form
          explode: true
          schema:
            type: integer
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
        '400':
          description: bad input parameter
    post:
      summary: ''
      operationId: post-account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message:
                    type: string
                    x-stoplight:
                      id: dnv5o1bwpph8a
                    default: New Balance Updated
                    example: New Balance Updated
              examples:
                Example 1:
                  value:
                    Message: New Balance Updated
      x-stoplight:
        id: 912kipsbtgxja
      description: Post Money To A/C
      parameters:
        - schema:
            type: string
          in: query
          name: account_number
          description: Enter a account number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountType:
                  type: string
                  x-stoplight:
                    id: 33sn33u1f8p26
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        id:
          type: string
          description: User id
          example: '1'
        name:
          type: string
          description: Users first name
          example: Sanketh
        last_name:
          type: string
          description: Users last name
          example: Shanbhag
        email:
          type: string
          description: Users email
          example: sanketh.shanbhag@smartbear.com
        phone:
          type: string
          description: Balance
          example: '1000.0'
        address:
          type: string
          description: Users address
          example: 'Bangalore, India'
